modLoader = "javafml"
loaderVersion = "[45,)"
license = "Custom"

[[mods]]
modId = "brewery"
version = "${version}"
displayName = "[Let's Do] Brewery"
authors = "satisfy"
description = '''
Ozapft is! Brau Bier, beiss in a Bretzn – willkomme zum Braufescht!'''
logoFile = "pack.png"

[[dependencies.brewery]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.brewery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.brewery]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.brewery]]
modId = "farm_and_charm"
mandatory = true
versionRange = "[0.0.1,)"
ordering = "AFTER"
side = "BOTH"